spring:
  config:
    import: "configserver:"
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILE:dev}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

# MongoDB, RabbitMQ, JWT, and Eureka are defined in Config Server
# See /config-service/src/main/resources/configs/notification-service.yaml
