spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:api-gateway/.env[.properties]
      - optional:file:src/api-gateway/.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-route
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/identity/**
              filters:
                - StripPrefix=1
            - id: profile-route
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/profile/**
              filters:
                - StripPrefix=1
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${GATEWAY_PORT:8080}

app:
  api:
    public-endpoints:
      - /identity/api/auth/login
      - /identity/api/auth/register
