spring:
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
      - optional:file:.env[.properties]
      - optional:file:api-gateway/.env[.properties]
      - optional:file:src/api-gateway/.env[.properties]
  application:
    name: api-gateway

server:
  port: ${GATEWAY_PORT:8080}
