spring:
  config:
    import: "configserver:"
  application:
    name: wallet-service
  profiles:
    active: ${SPRING_PROFILE:dev}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6

# Các cấu hình datasource, jwt, eureka... được định nghĩa trong Config Server
# Xem /config-service/src/main/resources/configs/wallet-service.yaml
