server:
  port: ${FLASHCARD_SERVER_PORT:8085}

spring:
  application:
    name: flashcard-service
  data:
    mongodb:
      uri: mongodb+srv://senko:123@clustercard.bdhmypa.mongodb.net/flashcard_db?retryWrites=true&w=majority
      socket-timeout-ms: 30000
      connection-timeout-ms: 30000
  cloud:
    openfeign:
      client:
        config:
          wallet-service:
            url: http://localhost:8084
          default:
            connect-timeout: 10000
            read-timeout: 10000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.cardy.flashcardServer: TRACE
