spring:
  datasource:
    url: ${IDENTITY_DB_URL}
    username: ${IDENTITY_DB_USERNAME}
    password: ${IDENTITY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true

jwt:
  issuer: seika-identity-service
  secret: ${JWT_SECRET}
  access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}

app:
  services:
    profile: ${PROFILE_SERVER_URL}

messaging:
  events:
    identity-exchange: ${IDENTITY_EVENTS_EXCHANGE:identity.events}
    user-registered-routing-key: ${USER_REGISTERED_ROUTING_KEY:user.registered}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always

management:

  otlp:
    tracing:
      endpoint: "http://tempo:4317"
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'