server:
  port: ${NOTIFICATION_SERVER_PORT:8087}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
spring:
  mongodb:
    uri: ${NOTIFICATION_MONGO_URI}
    database: ${NOTIFICATION_MONGO_DATABASE}
