server:
  port: ${QUIZ_SERVER_PORT:8087}

spring:
  application:
    name: quiz-service
  data:
    mongodb:
      uri: ${QUIZ_DB_URI}

logging:
  level:
    root: WARN
    com.seika: INFO

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
