spring:
  config:
    import: "configserver:"
  application:
    name: identity-service
  profiles:
    active: ${SPRING_PROFILE:dev}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

# Các cấu hình datasource, Eureka... được định nghĩa trong Config Server
# Xem /config-service/src/main/resources/configs/identity-service.yaml
