spring:
  config:
    import: "configserver:"
  application:
    name: identity-service
  profiles:
    active: ${SPRING_PROFILE:dev}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 6

jwt:
  issuer: seika-identity-service
  secret: 8db8d4987f6a51ed76090464c02e06205d68fc0b8d8f024e6c3c57cb67da7a9b
  access-token-expiration-minutes: 60

# Các cấu hình datasource, Eureka... được định nghĩa trong Config Server
# Xem /config-service/src/main/resources/configs/identity-service.yaml
