spring:
  # Config sẽ được lấy từ Config Server thông qua bootstrap.yaml
  application:
    name: profile-service

# Các cấu hình datasource, JWT, Eureka... được định nghĩa trong Config Server
# Xem /config-service/src/main/resources/configs/profile-service.yaml
